app = "webosu"
primary_region = "iad"

[build]
  [build.args]
    DEFAULT_SKIN_URL = "https://github.com/noahs710/webosu/releases/download/skins/default.osk"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0

[[http_service.checks]]
  interval = "30s"
  timeout = "5s"
  grace_period = "10s"
  method = "GET"
  path = "/api/health"

[mounts]
  source = "webosu_data"
  destination = "/data"

